tutofix/book-module/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tutofix/book-module/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <description>Title of the book</description>
    <label>Author</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

tutofix/book-module/main/default/objects/Book__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the book</description>
    <label>Title</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

tutofix/book-module/main/default/classes/BookHandler.cls
public class BookHandler {
    
    public void run(List<Book__c> triggerBooks) {
        updateTitleField(triggerBooks);
        updateAuthorField(triggerBooks);
    }
    
    public void updateTitleField(List<Book__c> triggerBooks) {
        for (Book__c book : triggerBooks) {
            if(book.title__c == null) {
                book.title__c = 'Unknown title from module';
            }
        }
    }
    
    public static void updateAuthorField(List<Book__c> triggerBooks) {
        for (Book__c book : triggerBooks) {
            if(book.author__c == null) {
                book.author__c = 'Unknown author from module';
            }
        }
    }
}