one shared folder for all modules solution/tutofix/all-modules/game-module/main/default/objects/Game__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

tutofix/game-module/main/default/classes/GameHandler.cls
public class GameHandler {
    
    public void run(List<Game__c> triggerGames) {
        updateNameField(triggerGames);
        updateConditionField(triggerGames);
    }
    
    public void updateNameField(List<Game__c> triggerGames) {
        for (Game__c game : triggerGames) {
            if(game.name == null) {
                game.name = 'Unknown name from module';
            }
        }
    }
    
    public static void updateConditionField(List<Game__c> triggerGames) {
        for (Game__c game : triggerGames) {
            if(game.condition__c == null) {
                game.condition__c = 'Unknown condition from module';
            }
        }
    }
}